version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: helpdesk-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: helpdesk
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: